# Generated by Django 3.2.6 on 2021-12-06 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_contactinfo1_student1_teacher1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fd1', models.CharField(max_length=50)),
                ('fd2', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testApp.parent')),
                ('fd3', models.CharField(max_length=50)),
                ('fd4', models.CharField(max_length=50)),
            ],
            bases=('testApp.parent',),
        ),
        migrations.CreateModel(
            name='SubChild',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testApp.parent')),
                ('fd5', models.CharField(max_length=50)),
            ],
            bases=('testApp.parent',),
        ),
    ]
