# Generated by Django 3.2.6 on 2021-09-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.CharField(max_length=50)),
                ('moviename', models.CharField(max_length=50)),
                ('hero', models.CharField(max_length=50)),
                ('heroin', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
